# Generated by Django 5.0 on 2025-02-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acao', 'Ação'), ('fii', 'FII'), ('etf', 'ETF'), ('outro', 'Outro')], max_length=10)),
                ('ticker', models.CharField(max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_compra', models.DateField()),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
