# Generated by Django 5.0 on 2025-02-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='dividendos_recebidos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
